### ISSUE TITLE
seeders please come back

### ISSUE THREAD

**Issue by sergeevii123** [snakers4/open_stt#10]
can't download public_youtube1120.tar.gz from torrent
the downloading process stopped at 107G no seeders to download more

**Comment by snakers4** [comment]
We are seeding
![image](https://user-images.githubusercontent.com/12515440/60710372-38f4a000-9f1b-11e9-86b5-b9b9762daa66.png)

Please try various torrent clients, sometimes transmission glitched for when when using academic torrents
Also note that some torrent clients glitch with such large files

**Comment by sergeevii123** [comment]
ok, will try another clients

**Comment by snakers4** [comment]
Please contact me personally in private if the issue persists
