### ISSUE TITLE
Неправильная контрольная сумма

### ISSUE THREAD

**Issue by exelents** [snakers4/open_stt#16]
https://github.com/snakers4/open_stt/blob/379490e17b800ef9ba152d2c4011ad371a4dd9c1/md5sum.lst#L38

два раза скачал этот файл, и оба раза сумма равнялась 
308e16298bdc74670d1c0124cbf4e7bb
тут либо файл не обновили на сервере, либо хеш указали старый.

**Comment by snakers4** [comment]
@islanna

**Comment by Islanna** [comment]
Проверила md5sum на локальном сервере, похоже действительно по ссылке неправильный файл. 
Исправим в ближайшее время.

**Comment by snakers4** [comment]
Или DO стал пережимать файлы дополнительно
Надо проверять

**Comment by Islanna** [comment]
Архив верный, похоже DO пережал файлы, нужно пересчитать контрольные суммы для новых датасетов.

**Comment by Islanna** [comment]
6452a3bb816ae325c51e131fceae85e039da3b18
@exelents 
Пофиксили ссылку на файл

**Comment by snakers4** [comment]
открывайте если актуально

**Comment by snakers4** [comment]
reuploaded the file
