### ISSUE TITLE
Unexpected EOF of radio-v4 mp3 archive

### ISSUE THREAD

**Issue by olesyaksyon** [snakers4/open_stt#18]
Hi, 

I downloaded radio-v4 mp3 tar.gz from v10 release, the archive was downloaded successfully, but command

tar -xvzf radio_v4_mp3.tar.gz

ends with the mistake:

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by snakers4** [comment]
Did you check the checksum?

**Comment by olesyaksyon** [comment]
I've checked, it didn't match.

output:
f933f400494d4c883ef9bfd0f1f6ddcb
original:
7c2273a5b8c3cc10df3754dbe9c783e1

I used hashlib for check

**Comment by nurtdinovadf** [comment]
@olesyaksyon did you get the same hash from multiple download attempts, or was it the only attempt?

**Comment by snakers4** [comment]
Also we used `md5sum ` for hashes (@nurtdinovadf ?)

**Comment by nurtdinovadf** [comment]
@snakers4 yes, that's correct, we used ```md5sum```, i guess, it is equivalent to ```hashlib.md5```, but in some cases they can differ https://stackoverflow.com/questions/5693360/why-is-an-md5-hash-created-by-python-different-from-one-created-using-echo-and-m
@olesyaksyon could you check the hash using md5sum?

**Comment by olesyaksyon** [comment]
@nurtdinovadf hi! sorry for late answer. I've checked with shell

cat radio_v4_mp3.tar.gz | md5sum
f933f400494d4c883ef9bfd0f1f6ddcb  -

now it is the same.

**Comment by olesyaksyon** [comment]
but still EOF

**Comment by snakers4** [comment]
Replaced CDN links with links wo CDN
Probably this was the issue

**Comment by nurtdinovadf** [comment]
@olesyaksyon I've downloaded and checked the sum, it did match with the original. However, if your host is in a country with some internet access restrictions, it may cause problems while downloading. I suggest you try to download a small sample first (radio_v4_add) and if you succeed, try to download the large archive once again. Please use updated links for all your downloads this time (https://github.com/snakers4/open_stt#links). Using VPN may also help.

**Comment by olesyaksyon** [comment]
now it is ok, thank you!
