### ISSUE TITLE
Broken torrent file for downloading wav file

### ISSUE THREAD

**Issue by ec49ce** [snakers4/open_stt#20]
For a WAV version of the dataset (v1.0) torrent file for downloading is damaged.
https://academictorrents.com/details/a7929f1d8108a2a6ba2785f67d722423f088e6ba

**Comment by snakers4** [comment]
The above link is for v1.0

What seems to be the exact problem?

**Comment by ec49ce** [comment]
Size of torrent file is 41kB.
link to [file](https://academictorrents.com/download/a7929f1d8108a2a6ba2785f67d722423f088e6ba.torrent)

When I try to add him to utorrent - program show following error.  
![2019-12-11 194653](https://user-images.githubusercontent.com/20902014/70641730-1e9fba80-1c4f-11ea-96ab-c34cddc844f8.png)

I try to download other torrent file for ver.0.5 - his size was about 6MB and utorrent add him correctly.

**Comment by snakers4** [comment]
https://github.com/snakers4/open_stt/#via-torrent

A recommended way to download is to use aria2 

Does it work for you?

**Comment by ec49ce** [comment]
> https://github.com/snakers4/open_stt/#via-torrent
> 
> A recommended way to download is to use aria2
> 
> Does it work for you?

Thank you.
everything passed good when I used aria2.
