### ISSUE TITLE
Text normalizaton

### ISSUE THREAD

**Issue by Oktai15** [snakers4/open_stt#21]
Could you share text normalization pipeline for russian lang? I suppose you did something like this:
https://github.com/NVIDIA/NeMo/blob/f5f09838b96ab48f40d97c100fbcfc5b7f1ac59e/collections/nemo_asr/nemo_asr/parts/cleaners.py

**Comment by snakers4** [comment]
Hi,

We were planning on sharing the S2S model based on our pipeline.
We are not planning on sharing the pipeline itself.
