### ISSUE TITLE
Can't download via torent

### ISSUE THREAD

**Issue by 32r81b** [snakers4/open_stt#22]
@snakers4 , thank you for you job.
I find torrent client that open torrent without errors (Vuze Bittorent or Deluge), but there are no online peers :(. Or may be it is wrong behavior because 'unsupported piece size (1 GB)!'?

**Comment by snakers4** [comment]
have you tried `aria2c`?
https://github.com/snakers4/open_stt/#via-torrent

I am seeding
![image](https://user-images.githubusercontent.com/12515440/71416846-65d87300-2673-11ea-9283-c255c5f1dbb7.png)

**Comment by 32r81b** [comment]
I used torrent client om Windows machine. When I use aria2 all is fine.
Thank you.
