### ISSUE TITLE
public_youtube700 is subset of public_youtube1200?

### ISSUE THREAD

**Issue by Oktai15** [snakers4/open_stt#23]
Hi, @snakers4! 

Public_youtube700 is subset of public_youtube1200 or they are various datasets?

and the same question about public_youtube1120_hq

**Comment by snakers4** [comment]
different

hq I believe is a small subset with a higher audio quality

**Comment by Oktai15** [comment]
@snakers4, hq is small subset of public_youtube1200/public_youtube700 or independent dataset too?

**Comment by snakers4** [comment]
To be honest I do not remember exactly
But most likely it is a version of some subset of YouTube data with higher quality
