### ISSUE TITLE
Ordering of the audio files.

### ISSUE THREAD

**Issue by anidhi** [snakers4/open_stt#24]
Hi, 
This might be a stupid question, but i was trying to use the radio_2 dataset and upon downloading (mp3+txt), I am having trouble understanding the order in which the audio files correlate with each other. My questions are:

1.  Are the audio files in folders continuous? And are they **alphabetically** continuous? 
For e.g., if I am in folder 00, and I play an audio file 0d5d45dbfeba.mp3 and then alphabetically next, 0e4154bfc77c.mp3, is the content continuous i.e the actual content has been segmented into these files? 
If not, are the mp3 files ordered and if yes, what is the ordering?

2. Some segmentations seem to have been broken down into letters. This is normally seen at the start and end of the sentence. I am assuming this is because words have been cut down. My question here is, is this transcription done by an automated software?

This is an amazing dataset. I really appreciate any help on the above issues. 
Regards,

**Comment by snakers4** [comment]
Hi,

> Are the audio files in folders continuous? 

No

> And are they alphabetically continuous

No
Their location is based on SHA1 hashes
As far as I know, cryptographic hashes are not really continuous
You may consider file location to be random

> mp3+txt

Do you mean the publicly available subset of radio + public speech?

> Some segmentations seem to have been broken down into letters. This is normally seen at the start and end of the sentence. I am assuming this is because words have been cut down.

This is a known bug of our algorithms
In this dataset it is actually already heavily mitigated

> is this transcription done by an automated software?

We were not planning to publish our data processing pipelines

**Comment by anidhi** [comment]
Hi,
Thanks, that is helpful.
However, I am trying to work on STT translation from Russian -> X (any other language) and it would be helpful if the audio files could be continuous and not randomly arranged. 
Is there an ordered dataset for this ? It is for non-commercial purpose and I will definitely provide citations and links to your work.
I am working on the radio_2 dataset (https://ru-open-stt.ams3.digitaloceanspaces.com/radio_2_mp3.tar.gz). It is only Radio data (not public speech). 
Regards,

**Comment by snakers4** [comment]
> Is there an ordered dataset for this ?

Not that I know of

To be honest I cannot undestand why this matters
STT applications usually require small batched files
