### ISSUE TITLE
Q: Is there annotations for radio_v4 dataset?

### ISSUE THREAD

**Issue by ixomaxip** [snakers4/open_stt#25]
Hi, @snakers4!

I'd like to try radio_v2 dataset.

I've seen references to *.txt file in the radio_v4_manifest.csv. But I couldn't find these ones in archives radio_v4*.tar.gz.

Have this dataset any annotations?

**Comment by snakers4** [comment]
> Have this dataset any annotations?

radio_v4.tar.gz
this particular file does not

**Comment by ixomaxip** [comment]
Thank you for the answer!
