### ISSUE TITLE
Двойные буквы и дефисы для тестовых данных

### ISSUE THREAD

**Issue by nshmyrev** [snakers4/open_stt#26]
В тестах много сдвоенных букв, вроде 

```
что можно эксплуатировать людеей
```

а также отсутствуют дефисы, что делает результат не совсем удобночитаемым.

Предлагаю внести следующие исправления в asr_calls_2_val и public_youtube700_val

[text-youtube.txt](https://github.com/snakers4/open_stt/files/4345383/text-youtube.txt)
[text-calls.txt](https://github.com/snakers4/open_stt/files/4345385/text-calls.txt)

Могу преобразовать их в другой формат, если нужно

**Comment by ixomaxip** [comment]
лучше оставить исходный формат путей до файлов как в манифестах

**Comment by snakers4** [comment]
> В тестах много сдвоенных букв

Сколько записей из скольки?

**Comment by nshmyrev** [comment]
В youtube 500 из 7140：

[text.txt](https://github.com/snakers4/open_stt/files/4347839/text.txt)
[text.diff.txt](https://github.com/snakers4/open_stt/files/4347840/text.diff.txt)

**Comment by snakers4** [comment]
Спасибо

Не до конца понял, вероятно `text.txt` это уже поправленный
Если хотите, можете выложить свои diff-ы + скрипт для правки в тикет, я добавлю ссылку в README
Но в архивах пока не вижу смысла править по целому ряду причин

И да, тут нужно учитывать, это артефакт людей
То есть грубо говоря при ручной разметке всегда есть 5-6 CER тупо по дефолту
Не в дублях - так наберется в "ээээ" или "хм" или в транскрипции слов "вне" словаря

Другими словами - общие датасеты такие общие

**Comment by snakers4** [comment]
если метрики не отличаются - то проще не запариваться
