### ISSUE TITLE
нет txt файлов  в public_speech.tar.gz

### ISSUE THREAD

**Issue by Advencher** [snakers4/open_stt#27]
Здравствуйте, пользуюсь Вашим датасетом в учебном проекте, как видно из названия проблемы, не нашел .txt транскрипций в publich_speech.tar.gz, хотя они указаны в public_speech_manifest.csv (скачивал с торрента). При этом все wav файлы

**Comment by Advencher** [comment]
wav файлы на месте

**Comment by Advencher** [comment]
хотя возможно они и не должны быть аннотированы

**Comment by snakers4** [comment]
Доступ к этой разметке даём по запросу
Для учебного проекта данных даже v0.5 избыточно на порядок

**Comment by Advencher** [comment]
Здравствуйте, понял, благодарю

Я уже заполнил форму для учебного проекта (студент СПбГУАП).

Advencher ник на github, буду очень благодарен, если предоставите доступ,
если нужны подтверждения, что я учусь в вузе и проект связан с большой
выборкой для датасета, то все предоставлю. (обучаю Mozilla DeepSpeech)

С уважением, Архипов А. М.

**Comment by buriy** [comment]
Для обучения mozilla deepspeech версии 0.5 датасета тоже вполне достаточно.

**Comment by Advencher** [comment]
Да достаточно, но я также пытаюсь добиться большей точности WER, чем в
аналогичных работах (СПБГУ обучили на 35% процентов).
То есть хочу прогнать через максимальное количество часов, у меня так же
есть скрипт, который с Ютуба субтитры качает, но в связи со скорой защитой,
мне не хватает выборки.
А в public_speech заинтересован, тк deepspeech может лучше распознавать
обычную (не книжную) речь.
В общем, я могу дать гарантию, что дальше моего жёсткого диска эти
аннотации никуда не уйдут, могу подписать DMCA.

**Comment by snakers4** [comment]
можно скачать датасет с ютуба который доступен на гугл диске по ссылке

**Comment by Advencher** [comment]
Хорошо, спасибо большое за ответ и разъяснения

Если все таки появится возможность предоставить доступ к public_speech, то
буду Вам благодарен

Я просто не знал, что v1.0 это закрытая часть датасета

С уважением Архипов А. М.

**Comment by Advencher** [comment]
здравствуйте, хотел указать на проблемы с wav файлами датасета v0.5 на
торренте - некоторые файлы не загружаются (youtube и audiobooks - главные
из них). возможно их уже никто не раздает.
так что в "обходную" приходится скачивать mp3 и преобразовывать их в wav,
действительно ли эти файлы не доступны на торренте или это временный баг
С уважением Архипов А. М.

пн, 23 мар. 2020 г. в 09:55, Aleks Maksovich <dr.advencher@gmail.com>:

**Comment by snakers4** [comment]
> с wav файлами датасета v0.5 на
торренте - некоторые файлы не загружаются (youtube и audiobooks - главные
из них). возможно их уже никто не раздает.

v0.5 не поддерживается - я подержал месяца 2 его после релиза 1.0
энное число дней назад выключил его торрент
вы можете просто взять гайд из доки по торренту
и найти нужные вам файлы в v1.0
там они отдельно

**Comment by snakers4** [comment]
mp3 были по прямой ссылке, их пока закрыли
когда  / если будем наводить порядок, сведем все ветки в opus

**Comment by Advencher** [comment]
да я видимо неправильно сформулировал извиняюсь
вот этот торрент с github перед таблицей с датасетом
[image: image.png]
https://academictorrents.com/details/a7929f1d8108a2a6ba2785f67d722423f088e6ba
- то есть я пытаюсь качать архивы отсюда это и есть v1.0, но из него я
качаю то, что доступно

при этом ни ctorrent, transmission, или deluge не начинают
скачку (transmission просто вылетает без какой-либо ошибки)
то есть какие-то архивы и файлы не скачиваются из этого торрента в гайде
(youtube и audiobooks), но до этого я смог скачать вот эти архивы:
[image: image.png]
но какие-либо другие не скачиваются

чт, 26 мар. 2020 г. в 12:13, Alexander Veysov <notifications@github.com>:

**Comment by snakers4** [comment]
> при этом ни ctorrent, transmission, или deluge не начинают скачку (transmission просто вылетает без какой-либо ошибки)

было такое
беда в том, что он очень большой
пробуйте торрент-клиент по гайду
в 99% случаев у тех у кого была такая беда помогало

**Comment by Advencher** [comment]
то есть я пытаюсь прицельно скачать этот список, но безрезультатно через
разные программы:
[image: image.png]

чт, 26 мар. 2020 г. в 12:25, Aleks Maksovich <dr.advencher@gmail.com>:

**Comment by snakers4** [comment]
фотки не приходят
пробуйте aria2c

**Comment by Advencher** [comment]
Хорошо, спасибо за помощь и ответы, попытаюсь с aria2c.
Ну там на фотках просто список архивов которые никак не могут начать
загружаться через торрент.

С уважением Архипов А.М.

**Comment by Advencher** [comment]
Здравствуйте еще раз, извиняюсь, если отвлекаю, хотел задать последний
вопрос по поводу архивов:
Например эти архивы нужно объединить перед распаковкой? Т.к. только
gz_aa открывается (я пробовал объединить в 131гб архив с помощью cat, но
выдавал ошибку, что архив поврежден)
В общем, мне кажется, что когда я открываю gz_aa, вместе с ним открываются
и остальные
audiobooks_2.tar.gz_aa
audiobooks_2.tar.gz_ab
audiobooks_2.tar.gz_ac
audiobooks_2.tar.gz_ad
audiobooks_2.tar.gz_ae
audiobooks_2.tar.gz_af
audiobooks_2.tar.gz_ag


чт, 26 мар. 2020 г. в 13:12, Aleks Maksovich <dr.advencher@gmail.com>:

**Comment by snakers4** [comment]
здесь тяжело сказать что-то без конкретных команд которыми вы что-то делаете с файлами

**Comment by snakers4** [comment]
также я точно не помню, но кажется мы разбивали на части архивы в старых релизах

**Comment by 32r81b** [comment]
> В общем, мне кажется, что когда я открываю gz_aa, вместе с ним открываются
и остальные

Необходимо скачать все файлы и распаковать командой `cat audiobooks_2.tar.gz_* | tar xvfz -`
