### ISSUE TITLE
Опыт применения open_stt для обучения распознавания телефонных разговоров на DeepSpeech

### ISSUE THREAD

**Issue by 32r81b** [snakers4/open_stt#28]
Ситуация: экспериментирую с распознаванием голоса в телефонных разговорах. Исходное качество 8 кГц:
![image](https://user-images.githubusercontent.com/8361949/77844813-709f2880-71cb-11ea-86c4-bdf5687762a5.png)
Своих размеченных данных всего на 3,5 часа.

### Моя стратегия:

- Исключаю плохо размеченные записи согласно public_exclude_file_v5.csv + исключаю аудио короче 3 и длиннее 10 секунд.
- Конвертирую все оставшееся под нужный формат. Например, было:

![image](https://user-images.githubusercontent.com/8361949/77844916-4c901700-71cc-11ea-95a4-0e484f24b3da.png)

Стало после конвертации:
![image](https://user-images.githubusercontent.com/8361949/77844924-57e34280-71cc-11ea-9d9c-16f40a98b9c4.png)

- Делю все записи в соотношении 80% - train, 20% - dev. Финальную проверку делаю на своих размеченных данных. Т.к. своих данных мало они вообще не участвуют в обучении. Лингвистическая модель собирается тоже по своим данным т.к. много специфичных слов. далее обучаю на deepspeech.

### Результат на public_youtube1120_hq
Исключено 182853 записей, оставляю для обучения 186770 (приблизительно 138 часов). В результате обучения на dev получаю validation loss: 69.137811. При прогоне модели на моих данных получаю loss в два раза выше loss: 126.084709 (WER: 0.594781, CER: 0.404845).

### Результат на asr_public_phone_calls_2
Исключено 410507 записей, оставляю для обучения 193290 (приблизительно 140 часов). В результате обучения на dev получаю validation loss: 58.780545. При прогоне модели на моих данных снова получаю loss в два раза выше loss: 120.485580 (WER: 0.582977, CER: 0.405931).

### Результат объединения public_youtube700, public_youtube1120_hq, asr_public_phone_calls_1, asr_public_phone_calls_2, asr_calls_2_val
После всех исключений получается примерно 670 часов. В результате обучения на dev получаю validation loss: 46.687967. При прогоне модели на моих данных получаю loss: 91.705399 (WER: 0.383752, CER: 0.268075).
Тут я решил немного поиграть с аугментацией. Но вопреки моим ожиданиям стало только хуже.
**Агрессивная аугментация** (-–data_aug_features_additive=0.3 -–data_aug_features_multiplicative=0.3 -–augmentation_freq_and_time_masking=True -–augmentation_speed_up_std=0.3 -–augmentation_pitch_and_tempo_scaling=True): получаю loss: 103.976425 (WER: 0.455561, CER: 0.306885).
**Не агрессивная аугментация** (-–data_aug_features_additive=0.1 -–data_aug_features_multiplicative=0.1 -–augmentation_freq_and_time_masking=True -–augmentation_speed_up_std=0.1 -–augmentation_pitch_and_tempo_scaling=True): получаю loss: 94.959457 (WER: 0.388207, CER: 0.267716). Далее продолжил эксперименты без какой либо аугментации.

### Результат объединения public_youtube700, public_youtube1120_hq, asr_public_phone_calls_1, asr_public_phone_calls_2, asr_calls_2_val + private_buriy_audiobooks_2, radio_2
После всех исключений получается примерно 2130 часов. В результате обучения на dev получаю validation loss: 35.213670. При прогоне модели на моих данных получаю loss в: 83.400711 (WER: 0.358523, CER: 0.273550).

Вопросы к моим результатам:
1. Правильно ли я привел wav файлы к одному формату? Может надо проверить какие-то еще параметры аудио? Конвертация происходит примерно так:

```
import librosa
import soundfile as sf

sr = 8000

y, s = librosa.load(fname, sr=sr)
sf.write(fname_8k, y, sr, subtype='PCM_16')
```

2. Какие либо советы по добавлению новых датасетов из open_stt? Смущает, что при добавлении огромных датасетов private_buriy_audiobooks_2 и radio_2 обучающая выборка увеличилась с 670 до 2130 часов. Но при этом почти не улучшилась точность модели WER 0.38 → 0.36.
3. Какие либо советы по аугментации? Обучаю на открытых размеченных данных, а применяю модель разговорам по телефону.

Заранее спасибо.

**Comment by snakers4** [comment]
Обсуждение тренировки моделей выходит за рамки цели этого репозитория.

> Своих размеченных данных всего на 3,5 часа.

Как правило для получения какого-то качества на каком-то домене данных нужно на порядки больше.

> Смущает, что при добавлении огромных датасетов private_buriy_audiobooks_2 и radio_2 обучающая выборка увеличилась с 670 до 2130 часов. Но при этом почти не улучшилась точность модели WER 0.38 → 0.36.

Вероятно для вашей валидации они просто out-of-domain.

> Какие либо советы по аугментации? 

Общий совет - пытаться делать так, чтобы данные на тесте были похожи хоть как-то на данные на трейне.
