### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by Alex-Kopylov** [snakers4/open_stt#32]
Hi. I'm trying to download dataset on my PC via _download.sh_

Error "404: The specified blob does not exist.."

Python way is also broken and nobody seed the torrent.

**Comment by snakers4** [comment]
Hi,

I checked a couple of direct links, they seem to be working

Which blob exactly is missing?

Also checked my torrent client, for some reason it was paused
Now it's up
![image](https://user-images.githubusercontent.com/12515440/89112099-e6abe880-d466-11ea-992e-9689bf852b67.png)

**Comment by Alex-Kopylov** [comment]
> I checked a couple of direct links, they seem to be working
Yea. They work indeed. I've tried download only via .sh and .py files.

> Which blob exactly is missing?
**md5sum.log**
archives/asr_calls_2_val.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_phone_calls_1.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_phone_calls_2.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_stories_1.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_stories_2.tar.gz: ОШИБКА при открытии или чтении
archives/buriy_audiobooks_2_val.tar.gz: ОШИБКА при открытии или чтении
archives/private_buriy_audiobooks_2.tar.gz: ОШИБКА при открытии или чтении
archives/public_lecture_1.tar.gz: ОШИБКА при открытии или чтении
archives/public_series_1.tar.gz: ОШИБКА при открытии или чтении
archives/public_speech_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube1120_hq.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube1120.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube700.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube700_val.tar.gz: ОШИБКА при открытии или чтении
archives/radio_2.tar.gz: ОШИБКА при открытии или чтении
archives/radio_pspeech_sample_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/radio_v4_add_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/radio_v4_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/tts_russian_addresses_rhvoice_4voices.tar.gz: ОШИБКА при открытии или чтении
manifests/asr_calls_2_val.csv: ОШИБКА при открытии или чтении
manifests/asr_public_phone_calls_1.csv: ОШИБКА при открытии или чтении
manifests/asr_public_phone_calls_2.csv: ОШИБКА при открытии или чтении
manifests/asr_public_stories_1.csv: ОШИБКА при открытии или чтении
manifests/asr_public_stories_2.csv: ОШИБКА при открытии или чтении
manifests/buriy_audiobooks_2_val.csv: ОШИБКА при открытии или чтении
manifests/private_buriy_audiobooks_2.csv: ОШИБКА при открытии или чтении
manifests/public_lecture_1.csv: ОШИБКА при открытии или чтении
manifests/public_series_1.csv: ОШИБКА при открытии или чтении
manifests/public_speech_manifest.csv: ОШИБКА при открытии или чтении
manifests/public_youtube1120.csv: ОШИБКА при открытии или чтении
manifests/public_youtube1120_hq.csv: ОШИБКА при открытии или чтении
manifests/public_youtube700.csv: ОШИБКА при открытии или чтении
manifests/public_youtube700_val.csv: ОШИБКА при открытии или чтении
manifests/radio_2.csv: ОШИБКА при открытии или чтении
manifests/radio_pspeech_sample_manifest.csv: ОШИБКА при открытии или чтении
manifests/radio_v4_add_manifest.csv: ОШИБКА при открытии или чтении
manifests/radio_v4_manifest.csv: ОШИБКА при открытии или чтении
manifests/tts_russian_addresses_rhvoice_4voices.csv: ОШИБКА при открытии или чтении

> Also checked my torrent client, for some reason it was paused
Thank you. Going to take around 9 hours to download.

**Comment by Alex-Kopylov** [comment]
> I checked a couple of direct links, they seem to be working

Yea. They work indeed. I've tried download only via .sh and .py files.

> Which blob exactly is missing?

**md5sum.log**

archives/asr_calls_2_val.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_phone_calls_1.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_phone_calls_2.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_stories_1.tar.gz: ОШИБКА при открытии или чтении
archives/asr_public_stories_2.tar.gz: ОШИБКА при открытии или чтении
archives/buriy_audiobooks_2_val.tar.gz: ОШИБКА при открытии или чтении
archives/private_buriy_audiobooks_2.tar.gz: ОШИБКА при открытии или чтении
archives/public_lecture_1.tar.gz: ОШИБКА при открытии или чтении
archives/public_series_1.tar.gz: ОШИБКА при открытии или чтении
archives/public_speech_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube1120_hq.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube1120.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube700.tar.gz: ОШИБКА при открытии или чтении
archives/public_youtube700_val.tar.gz: ОШИБКА при открытии или чтении
archives/radio_2.tar.gz: ОШИБКА при открытии или чтении
archives/radio_pspeech_sample_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/radio_v4_add_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/radio_v4_manifest.tar.gz: ОШИБКА при открытии или чтении
archives/tts_russian_addresses_rhvoice_4voices.tar.gz: ОШИБКА при открытии или чтении
manifests/asr_calls_2_val.csv: ОШИБКА при открытии или чтении
manifests/asr_public_phone_calls_1.csv: ОШИБКА при открытии или чтении
manifests/asr_public_phone_calls_2.csv: ОШИБКА при открытии или чтении
manifests/asr_public_stories_1.csv: ОШИБКА при открытии или чтении
manifests/asr_public_stories_2.csv: ОШИБКА при открытии или чтении
manifests/buriy_audiobooks_2_val.csv: ОШИБКА при открытии или чтении
manifests/private_buriy_audiobooks_2.csv: ОШИБКА при открытии или чтении
manifests/public_lecture_1.csv: ОШИБКА при открытии или чтении
manifests/public_series_1.csv: ОШИБКА при открытии или чтении
manifests/public_speech_manifest.csv: ОШИБКА при открытии или чтении
manifests/public_youtube1120.csv: ОШИБКА при открытии или чтении
manifests/public_youtube1120_hq.csv: ОШИБКА при открытии или чтении
manifests/public_youtube700.csv: ОШИБКА при открытии или чтении
manifests/public_youtube700_val.csv: ОШИБКА при открытии или чтении
manifests/radio_2.csv: ОШИБКА при открытии или чтении
manifests/radio_pspeech_sample_manifest.csv: ОШИБКА при открытии или чтении
manifests/radio_v4_add_manifest.csv: ОШИБКА при открытии или чтении
manifests/radio_v4_manifest.csv: ОШИБКА при открытии или чтении
manifests/tts_russian_addresses_rhvoice_4voices.csv: ОШИБКА при открытии или чтении
...
I stopped executing. 
> Also checked my torrent client, for some reason it was paused

Thank you. Going to take around 9 hours to download.

**Comment by tdtce** [comment]
Hello!

Could you start your torrent client or downloading via torrent is no longer available?

**Comment by snakers4** [comment]
Looks like the torrent is up
But the tracker is down
![image](https://user-images.githubusercontent.com/12515440/91296967-2cc64480-e7a6-11ea-8c8b-f9503a04b3eb.png)

You can always download via direct links from azure
I will contact academictorrents

**Comment by tdtce** [comment]
> Looks like the torrent is up
> But the tracker is down
> ![image](https://user-images.githubusercontent.com/12515440/91296967-2cc64480-e7a6-11ea-8c8b-f9503a04b3eb.png)
> 
> You can always download via direct links from azure
> I will contact academictorrents

Thanks!

**Comment by snakers4** [comment]
I contacted the tracker's admins.
We resolved the problem.
Last time I saw it, it was seeding 5-10 megabytes per second.

**Comment by tdtce** [comment]
Yes! tracker works with nice speed. Thanks for the quick response!
