### ISSUE TITLE
Не могу скачать файл

### ISSUE THREAD

**Issue by KoldunAmba** [snakers4/open_stt#33]
Пытаюсь скачать датасет через aria2c, но нет сидов уже несколько дней. Может кто-нибудь на раздачу встать или подсказать в чем ещё может быть проблема, если сиды всё-таки есть?

**Comment by snakers4** [comment]
![image](https://user-images.githubusercontent.com/12515440/93871759-cdd9e980-fcd7-11ea-8f90-74dcabff030f.png)

fixed
please use direct links as a backup

**Comment by snakers4** [comment]
had to play with settings a bit more

PS
it is kind of cringe that 17 people who have downloaded did not even considered seeding

**Comment by snakers4** [comment]
https://github.com/snakers4/open_stt/issues/34
