### ISSUE TITLE
В private_buriy_audiobooks_2 нет буквы ё, а в private_buriy_audiobooks_2_val есть

### ISSUE THREAD

**Issue by stllfe** [snakers4/open_stt#37]
Я не могу, конечно, назвать это критическим моментом, но мне кажется, такая особенность данных должна быть отражена где-то в описаниях к датасетам. Если есть возможность, было бы супер получить обучающий датасет с буквой ё.

**Comment by snakers4** [comment]
Считаем по дефолту, что буквы `ё` нигде нет.

**Comment by stllfe** [comment]
Окей, спасибо. Если добавите в описания где-нибудь, невнимательным людям сэкономите часик другой на дебаге и препроцессинге :)

**Comment by snakers4** [comment]
ок
