### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Elvares** [snakers4/open_stt#41]
I tried to download datasets. I launched download.py but got this 
"urllib.error.HTTPError: HTTP Error 404: The specified blob does not exist."
How does fix it?

**Comment by snakers4** [comment]
We have not checked the `download.py` for quite some time.
With which URL is there an error?

**Comment by Elvares** [comment]
this url = "https://azureopendatastorage.blob.core.windows.net/openstt/ru_open_stt_opus/" uses in download.py

**Comment by snakers4** [comment]
This is a base url to which paths are supposed to be appended

**Comment by snakers4** [comment]
I checked the URLs and mirror URLs - they were working
If the download scripts are obsolete - the PRs appreciated to fix them, they were auxiliary in any case
Also torrent downloads are an option
