### ISSUE TITLE
Проблема с торрентом

### ISSUE THREAD

**Issue by Elvares** [snakers4/open_stt#42]
При запуске торрента через utorrent пишет, что "невозможно загрузить название_торрента неподдерживаемый размер части (1.0 Гб)". При запуске торрента через transmission торрент не добавляется в список загрузок.

**Comment by snakers4** [comment]
Используйте aria2c - https://github.com/snakers4/open_stt/#via-torrent

С другими клиентами были проблемы, кроме qbit, но с ним они тоже появлялись
Все эти клиенты оферфитнуты для скачивания кино, очевидно
