### ISSUE TITLE
Missing text files

### ISSUE THREAD

**Issue by EgorDudyrev** [snakers4/open_stt#6]
Hi! 

New mp3 datasets have no text files with annotations. At least it's true for russian_single, ttl_russian_addresses and voxforge datasets.

![image](https://user-images.githubusercontent.com/17860670/57587670-4db34980-7511-11e9-91aa-999962d113e0.png)

**Comment by snakers4** [comment]
While I check you can use texts from the meta-data file

**Comment by snakers4** [comment]
I checked for several additional folders
Looks like there is a problem
Anyway, while I fix it, you can just use the texts from the meta-data file

**Comment by snakers4** [comment]
I fixed this issue and
- Reuploaded the fixed links;
- Fixed the torrent;

Please post more issues if you find problems with the dataset.
