### ISSUE TITLE
Links to YouTube videos

### ISSUE THREAD

**Issue by dimaxano** [snakers4/open_stt#8]
Hey! I'm working on creating russian Visual Speech Recognition dataset. So I'm very interested whether it is possible to provide links to YouTube videos that were used for creating youtube part of open_sst?

**Comment by snakers4** [comment]
Hi Dmitry!

Many thanks for your interest in our dataset.

> possible to provide links to YouTube videos that were used for creating youtube part of open_sst

We will never publish this information as a public part of the dataset for some reasons.

If you plain to contribute your work to public in any form, please contact us [here](mailto:open_stt@googlegroups.com) we will see what we can do.

**Comment by dimaxano** [comment]
Not sure if that will be possible, but if yes, I'll contact you. Thanks!
